MiniProject234/_01.MiniProject234.Web/Models/Shared/Common.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace _01.MiniProject234.Web.Models.Shared
{
    public class Common
    {
        public int TahunMulai { get; set; }

        public static List<Common> GetYear()
        {
            DateTime tahun = DateTime.Now;
            List<Common> list = new List<Common>();
            for (int i = 0; i <= 20; i++)
            {
                Common c = new Common();
                c.TahunMulai = tahun.Year;
                list.Add(c);
                tahun = tahun.AddYears(-1);
            }
            return list;
        }

    }
    public class CommonEndYear
    {
        public int TahunAkhir { get; set; }

        public static List<CommonEndYear> GetYear()
        {
            DateTime tahun = DateTime.Now.AddYears(10);
            List<CommonEndYear> list = new List<CommonEndYear>();
            for (int i = 0; i <= 30; i++)
            {
                CommonEndYear c = new CommonEndYear();
                c.TahunAkhir = tahun.Year;
                list.Add(c);
                tahun = tahun.AddYears(-1);
            }
            return list;
        }

    }
}

MiniProject234/_01.MiniProject234.Web/Models/Shared/Message.cs
using _03.MiniProject234.ModelView;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _01.MiniProject234.Web.Models.Shared
{
    public class Message
    {
        public string PropertyName { get; set; }
        public string PropertyValue { get; set; }

        public static List<Message> GetMessageErrorByModel(
            string modelName, ModelStateDictionary modelData)
        {
            List<Message> listError = new List<Message>();

            List<Message> listErrorByModel = GetMessageError(modelName, modelData);

            List<string> listFieldClass = typeof(x_sertifikasiModelView).GetProperties().Select(a => a.Name).ToList();

            foreach (var field in listFieldClass)
            {
                int index = listErrorByModel.FindIndex(n => n.PropertyName == field);

                Message message = new Message();
                message.PropertyName = field;

                if (index >= 0)
                {
                    message.PropertyValue = listErrorByModel[index].PropertyValue;
                }
                else { message.PropertyValue = string.Empty; }
                listError.Add(message);
            }
            return listError;
        }

        static List<Message> GetMessageError(string modelName,
            ModelStateDictionary modelData)
        {
            List<Message> listError = new List<Message>();
            foreach (KeyValuePair<string, ModelState>
                ms in modelData)
            {
                ModelState modelState = ms.Value;
                Message message = new Message();
                message.PropertyName =
                    GetFieldNameByObject(modelName + ".", ms.Key);

                if (modelState.Errors.Count > 0)
                {
                    message.PropertyValue =
                   string.Join("\n", GetErrorMessageByField(modelState));
                }
                else
                {
                    message.PropertyValue = string.Empty;
                }
                listError.Add(message);
            }
            return listError;
        }

        private static List<string> GetErrorMessageByField(
            ModelState modelState)
        {
            List<string> listError = new List<string>();
            foreach (ModelError error in modelState.Errors)
            {
                listError.Add(error.ErrorMessage);
            }

            return listError;
        }

        private static string GetFieldNameByObject(string v,
            string key)
        {
            if (key.Contains(v))
            {
                key = key.Replace(v, "");
            }
            return key;
        }
    }
}

MiniProject234/_01.MiniProject234.Web/Controllers/PelamarController.cs
using _01.MiniProject234.Web.Models;
using _02.MiniProject234.ModelAccess;
using _03.MiniProject234.ModelView;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _01.MiniProject234.Web.Controllers
{
    public class PelamarController : Controller
    {
        // GET: Pelamar
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult List(string paramSearch, int order, int? paramPage, int paramPageSize)
        {
            List<PelamarModelView> list = new List<PelamarModelView>();

            Int32 countDataDb = PelamarModelAccess.GetCountData(paramSearch);

            Paging pg = new Paging(countDataDb, paramPage, paramPageSize);

            ViewData["pg"] = pg;

            int page = (pg.CurrentPage - 1) * pg.PageSize;
            list = PelamarModelAccess.GetListAll(paramSearch, order, page, paramPageSize);

            if (countDataDb == 0)
            {
                return PartialView("DataKosong", list);
            }
            else
            {
                return PartialView("List", list);
            }

        }
        public ActionResult None()
        {
            return View();
        }
        public ActionResult Detail(Int32 paramId)
        {
            return PartialView(PelamarModelAccess.GetDetailsById(paramId));
        }
        public ActionResult Profil(Int32 paramId)
        {
            return PartialView(PelamarModelAccess.GetDetailsById(paramId));
        }
    }
}

MiniProject234/_01.MiniProject234.Web/Views/Shared/ModalPopup.cshtml
<!-- modal popup bootstrap - Edit Form -->
<!-- modal popup bootstrao - Popup Dosen -->
<div id="modal-form-list-menu" class="modal fade" role="dialog">
    <div class="modal-dialog" style="width:1200px">

        <!-- Modal Content -->
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header" style="background-color:#000066;color:white;">
                <button class="close close-list-modal" data-dismiss="modal" style="color:white">&times;</button>
                <h4 class="modal-title">
                    Judul Popup
                </h4>
            </div>

            <!-- Modal Body dan Footer -->
            <div class="row">
                <!-- Body menu kiri -->
                <div class="col-md-2" style="padding-top:15px;padding-left:27px">
                    <div class="list-group">
                        
                        <a class="btn btn-list-modal list-group-item details_list_item" id="item_Profile">Profile</a>
                        <a class="btn btn-list-modal list-group-item details_list_item" id="item_Biodata">Biodata</a>
                        <a class="btn btn-list-modal list-group-item details_list_item" id="item_PengalamanKerja">Pengalaman Kerja</a>
                        <a class="btn btn-list-modal list-group-item details_list_item" id="item_Pendidikan">Pendidikan</a>
                        <a class="btn btn-list-modal list-group-item details_list_item" id="item_Pelatihan">Pelatihan</a>
                        <a class="btn btn-list-modal list-group-item details_list_item" id="item_Sertifikasi">Sertifikasi</a>
                        <a class="btn btn-list-modal list-group-item details_list_item" id="item_SumberLowonganKerja">Sumber Lowongan Kerja</a>
                        <a class="btn btn-list-modal list-group-item details_list_item" id="item_Organisasi">Organisasi</a>
                        <a class="btn btn-list-modal list-group-item details_list_item" id="item_Keluarga">Keluarga</a>
                        <a class="btn btn-list-modal list-group-item details_list_item" id="item_Keahlian">Keahlian</a>
                        <a class="btn btn-list-modal list-group-item details_list_item" id="item_Lainlain">Lain-lain</a>
                        <a class="btn btn-list-modal list-group-item details_list_item" id="item_Dokumen">Dokumen</a>
                        <a class="btn btn-list-modal list-group-item details_list_item" id="item_Catatan">Catatan</a>
                        <a class="btn btn-list-modal list-group-item details_list_item" id="item_AktivasiAkun">Aktivasi Akun</a>
                        <a class="btn btn-list-modal list-group-item details_list_item" id="item_LihatTes">Lihat Tes</a>
                        <a class="btn btn-list-modal list-group-item details_list_item" id="item_HasilTes">Hasil Tes</a>
                    </div>
                </div>
                <!-- Body Content -->
                <div class="col-lg-10" style="margin-left: -25px">
                    <div class="modal-bind-content-list-menu"
                         id="details_pelamar_id" style="padding: 15px;">
                        @*ini content*@
                    </div>
                </div>
            </div>

        </div>

    </div>
</div>

<div class="modal fade modal-form" id="modal-form" role="dialog">
    <div class="modal-dialog" style="width:850px">
        <!-- modal content -->
        <div class="modal-content">
            <!-- modal header -->
            <div class="modal-header" id="modal-header" style="background-color:#000066">
                <button class="close" data-dismiss="modal" id="modal_form_button_close" style="color:white">
                    &times;
                </button>
                <h4 class="modal-title" id="modal-title"
                    style="font-weight: bold; color: antiquewhite;">
                </h4>
            </div>
            <!-- modal body dan footer -->
            <div class="div-bind-form" id="div-bind-form">

            </div>
        </div>
    </div>
</div>

<div class="modal fade modal-form-delete" id="modal-form-delete" role="dialog">
    <div class="modal-dialog" style="height: 120px;width:500px">
        <!-- modal content -->
        <div class="modal-content center">
            <!-- modal header -->
            <div class="modal-header" id="modal-header" style="background-color:#990000">
                <button class="close" data-dismiss="modal" id="modal_form_button_close" style="color:white">
                    &times;
                </button>
                <h4 class="modal-title" id="modal-title"
                    style="font-weight:bold; color:antiquewhite;">
                </h4>
            </div>
            <!-- modal body dan footer -->
            <div class="div-bind-form" id="div-bind-form" style="padding-top:20px">

            </div>
        </div>
    </div>
</div>

<style>
    .btn-list-modal{
        text-align: initial;
    }
    .btn{
        font-size: 12px;
    }
    .btn:hover,
    .btn:focus {
        color: #6C6CC5;
    }
</style>

MiniProject234/_01.MiniProject234.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <!--DatePicker stylesheet-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("XSis 2.0", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav mr-auto">
                    <li class="nav-item dropdown">
                        <a class="dropdown-toggle btn" type="button" data-toggle="dropdown" style="color:#F7F7FA">Menu 1 <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Submenu 1</a></li>
                            <li><a href="#">Submenu 2</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="dropdown-toggle btn" type="button" data-toggle="dropdown" style="color:#F7F7FA">Menu 2 <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Submenu 1</a></li>
                            <li><a href="#">Submenu 2</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="dropdown-toggle btn" type="button" data-toggle="dropdown" style="color:#F7F7FA">Menu 3 <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Submenu 1</a></li>
                            <li><a href="#">Submenu 2</a></li>
                        </ul>
                    </li>
                </ul>

                <div class="dropdown menu-akun">
                    <a class="dropdown-toggle btn" type="button" data-toggle="dropdown" style="color:#F7F7FA">Admin <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Ganti Password</a></li>
                        <li><a href="#">Logout</a></li>
                    </ul>
                </div>

            </div>
        </div>
    </div>

    <!-- Header -->
    <div class="title-bar content header">
        <h1>XSIS 2.0</h1>
    </div>
    <!-- /header -->
    <div class="container-fluid row">
        <div class="d-flex col-md-3 col-sm-12" id="wrapper">

            <!-- Sidebar -->
            <div class="border-right" id="sidebar-wrapper" style="margin-left:10px">
                <div class="list-group list-group-flush">
                    <a href="#" class="list-group-item list-group-item-action bg-light">Beranda</a>
                    <a href="@Url.Action("Index","Pelamar")" class="list-group-item list-group-item-action bg-light">Pelamar</a>
                    <a href="#" class="list-group-item list-group-item-action bg-light">Proses Pelamar</a>
                    <a href="#" class="list-group-item list-group-item-action bg-light">Penjadwalan</a>
                    <a href="#" class="list-group-item list-group-item-action bg-light">Tes</a>
                    <a href="#" class="list-group-item list-group-item-action bg-light">Bootcamp</a>
                    <a href="#" class="list-group-item list-group-item-action bg-light">Laporan</a>
                </div>
            </div>
            <!-- /#sidebar-wrapper -->
        </div>
        <!-- Page Content -->
        <div class="container d-flex col-md-9 content body-content" style="max-width:70%">
            @RenderBody()
            @Html.Partial("ModalPopup")
        </div>
    </div>
    <hr />
    <footer>
        <p style="margin-bottom:0px">&copy; @DateTime.Now.Year - Xsis 2.0 Bootcamp 234</p>
    </footer>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/commonfunction")
    @RenderSection("scripts", required: false)
    

    <!--datepicker plugin script-->
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
</body>
</html>