MiniProject234/_01.MiniProject234.Web/Controllers/KeluargaController.cs
using _01.MiniProject234.Web.Models.Shared;
using _02.MiniProject234.ModelAccess;
using _03.MiniProject234.ModelView;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _01.MiniProject234.Web.Controllers
{
    public class KeluargaController : Controller
    {
        // GET: Keluarga
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult List()
        {
            return PartialView(KeluargaModelAccess.GetListAll());
        }

        //Create Controller

        public ActionResult GetByTreeType(long treeTypeId)
        {
            ViewBag.ListRelationTree = new SelectList(KeluargaModelAccess.ByFamilyTree(treeTypeId), "idRelationType", "nameRelationType");
            return View(KeluargaModelAccess.ByFamilyTree(treeTypeId));
        }

        public ActionResult Create()
        {
            ViewBag.ListFamilyTree = new SelectList(KeluargaModelAccess.GetTreeType(), "id", "nameTree");
            ViewBag.ListRelationTree = new SelectList(KeluargaModelAccess.ByFamilyTree(0), "idRelationType", "nameRelationType");
            return PartialView("Create", new KeluargaModelView());
        }
        [HttpPost]
        public ActionResult Create(KeluargaModelView paramModel)
        {
            try
            {
                paramModel.createdBy = 1;
                paramModel.createdOn = DateTime.Now;

                if (ModelState.IsValid)
                {
                    return Json(new
                    {
                        success = KeluargaModelAccess.Insert(paramModel),
                        message = KeluargaModelAccess.Message
                    }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    List<Message> listMessage =
                     Message.GetMessageErrorByModel("paramModel", ModelState);

                    return Json(new
                    {
                        success = false,
                        message = listMessage
                    }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception hasError)
            {
                return Json(new
                {
                    success = false,
                    message = hasError.Message
                }, JsonRequestBehavior.AllowGet);
            }
        }

        #region Undone



        //public ActionResult Edit(Int32 paramId)
        //{
        //    ViewBag.ListTahunMulai = new SelectList(Common.GetYear(), "TahunMulai", "TahunMulai");
        //    return PartialView(x_sertifikasiModelAccess.GetDetailsBy(paramId));
        //}

        //[HttpPost]
        //public ActionResult EditPost(x_sertifikasiModelView paraModel)
        //{
        //    try
        //    {
        //        paraModel.modified_by = 1;
        //        paraModel.modified_on = DateTime.Now;

        //        return Json(new
        //        {
        //            success = x_sertifikasiModelAccess.Update(paraModel),
        //            message = x_sertifikasiModelAccess.Message
        //        }, JsonRequestBehavior.AllowGet);
        //    }
        //    catch (Exception hasError)
        //    {
        //        return Json(new
        //        {
        //            success = false,
        //            message = hasError.Message
        //        }, JsonRequestBehavior.AllowGet);
        //    }
        //}

        //public ActionResult Delete(Int32 paramId)
        //{
        //    return PartialView(x_sertifikasiModelAccess.GetDetailsBy(paramId));
        //}

        //[HttpPost]
        //public ActionResult Delete(x_sertifikasiModelView paraModel)
        //{
        //    try
        //    {
        //        paraModel.deleted_by = 1;
        //        paraModel.deleted_on = DateTime.Now;
        //        return Json(new
        //        {
        //            success = x_sertifikasiModelAccess.Delete(paraModel),
        //            message = x_sertifikasiModelAccess.Message
        //        }, JsonRequestBehavior.AllowGet);
        //    }
        //    catch (Exception hasError)
        //    {
        //        return Json(new
        //        {
        //            success = false,
        //            message = hasError.Message
        //        }, JsonRequestBehavior.AllowGet);
        //    }
        //}

        #endregion

    }
}

MiniProject234/_01.MiniProject234.Web/Views/Keluarga/Create.cshtml
@model _03.MiniProject234.ModelView.KeluargaModelView

<div class="modal-body" style="margin-left:20px;margin-right:20px">
    <div class="container py-5">
        <div class="col-md-12">
            <form id="form_create_keluarga">
                <div class="form-group row">
                    <div class="col-sm-6">
                        <label class="control-label" style="color: #023692">Jenis&nbsp;Susunan&nbsp;Keluarga&nbsp;*</label>
                        @Html.DropDownListFor(model => model.familyTreeTypeId, (IEnumerable<SelectListItem>)ViewBag.ListFamilyTree, "- Pilih -", new { @class = "form-control", @style = "width: 100%; max-width: 100%;" })
                        @Html.ValidationMessageFor(model => model.familyTreeTypeId, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-sm-6">
                        <label class="control-label" style="color: #023692">Hubungan&nbsp;Keluarga&nbsp;*</label>
                        @*@Html.DropDownListFor(model => model.familyRelationId, new List<SelectListItem>
                                                {
                                                   new SelectListItem{ Text="Ayah", Value = "1" },
                                                   new SelectListItem{ Text="Ibu", Value = "3" },
                                                   new SelectListItem{ Text="Anak", Value = "4" }
                                                }, "- PIlih -", new { @class = "form-control", @style = "width: 100%; max-width: 100%;" })*@
                        @Html.DropDownListFor(model => model.familyRelationId, (IEnumerable<SelectListItem>)ViewBag.ListRelationTree, "- Pilih -", new { @class = "form-control", @style = "width: 100%; max-width: 100%;" })
                        @Html.ValidationMessageFor(model => model.familyRelationId, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-6">
                        <label class="control-label" style="color: #023692">Nama&nbsp;*</label>
                        @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control", @style = "width: 100%; max-width: 100%;" } })
                        @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-sm-3">
                        <label class="control-label" style="color: #023692">Jenis&nbsp;Kelamin</label>
                        @Html.DropDownListFor(model => model.gender, new List<SelectListItem>
                            {
                               new SelectListItem{ Text="Pria", Value = "1" },
                               new SelectListItem{ Text="Perempuan", Value = "0" }
                            }, "- Pilih -", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.gender, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-sm-3">
                        <label class="control-label" style="color: #023692">Tgl.&nbsp;Lahir&nbsp;(yyyy-mm-dd)</label>
                        <div class='input-group date' id='myDatepicker'>
                            @Html.EditorFor(model => model.dob, new { htmlAttributes = new { @class = "form-control datepicker-dob inline", @type = "date", @style = "width: 100%; max-width: 100%;" } })
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                        @Html.ValidationMessageFor(model => model.dob, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-6">
                        <label class="control-label" style="color: #023692">Pendidikan</label>
                        @Html.EditorFor(model => model.educationLevelId, new { htmlAttributes = new { @class = "form-control", @style = "width: 100%; max-width: 100%;" } })
                        @Html.ValidationMessageFor(model => model.educationLevelId, "", new { @class = "text-danger" })

                    </div>
                    <div class="col-sm-6">
                        <label class="control-label" style="color: #023692">Pekerjaan</label>
                        @Html.EditorFor(model => model.job, new { htmlAttributes = new { @class = "form-control", @style = "width: 100%; max-width: 100%;" } })
                        @Html.ValidationMessageFor(model => model.job, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-12">
                        <label class="control-label" style="color: #023692">Catatan</label>
                        @Html.TextAreaFor(model => model.notes, 5, 40, htmlAttributes: new { @class = "form-control", @style = "width: 100%; max-width: 100%;" })
                        @Html.ValidationMessageFor(model => model.notes, "", new { @class = "text-danger" })
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal-footer">
    <input type="button" title="Batal"
           value="Cancel" class="btn btn-default" id="btn_cancel_form_keluarga"
           data-dismiss="modal" />
    <input type="button" title="Simpan"
           value="Save" class="btn btn-success btn_add_save_keluarga"
           id="btn_add_save_keluarga" />
</div>

<style>
    body {
        font-size: 13px;
    }

    .form-control[readonly] {
        background-color: white;
    }

    .input-group-addon {
        background-color: white;
    }
</style>

<script>
    flatpickr('.datepicker-dob', {
        dateFormat: 'Y-m-d',
        maxDate: "today"
        //maxDate: new Date().fp_incr(-6205) //set min 17th

    });

    $('#familyTreeTypeId').change(function () {
        $.ajax({
            url: '@Url.Action("GetByTreeType", "Keluarga")',
            type: 'get',
            data: { treeTypeId: $(this).val() }, // categoryId ini harus sama sprti d controller
            success: function (result) {
                $("#familyRelationId").html(result);
            }
        });
    });
</script>

MiniProject234/_01.MiniProject234.Web/Views/Keluarga/GetByTreeType.cshtml
@{
    Layout = null;
}

@model IEnumerable<_03.MiniProject234.ModelView.FamilyRelationModelView>

<option value="">- Pilih -</option>

@foreach (var item in Model)
{
    <option value="@item.idRelationType">@item.nameRelationType</option>
}

MiniProject234/_01.MiniProject234.Web/Views/Keluarga/List.cshtml
@model IEnumerable<_03.MiniProject234.ModelView.KeluargaModelView>

<div class="input-group" style="display:flex; align-items:baseline;">
    <h2>Keluarga</h2>
    <a class="btn btn-link button_grid_create_keluarga" title="Create" name="Create">
        <span class="glyphicon glyphicon-plus-sign" style="font-size:26px;color:black"></span>
    </a>
</div>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.familyRelationId)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dob)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.educationLevelId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.job)
        </th>
        <th></th>
    </tr>
    @if (Model != null)
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.familyRelationId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.gender)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.dob)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.educationLevelId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.job)
                </td>
                <td class="dropdown">
                    <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                        More
                        <span class="caret" style="color:white" />
                    </a>
                    <ul class="dropdown-menu">
                        <li><a id="btn_grid_edit_sertifikasi" name="btn_grid_edit_sertifikasi" title="Edit Sertifikasi" data-id="@item.id">Ubah</a></li>
                        <li><a id="btn_grid_delete_sertifikasi" name="btn_grid_delete_sertifikasi" title="Edit Sertifikasi" data-id="@item.id">Hapus</a></li>
                    </ul>
                </td>
            </tr>
        }

    }

</table>

<style>
    tr:nth-child(odd) > th, th {
        background-color: white;
    }

    a {
        color: #000066;
        text-decoration: none;
    }

    table {
        padding: 20px;
    }

    h2 {
        color: #000066;
        font-weight: bold;
    }
</style>