MiniProject234/_01.MiniProject234.Web/Controllers/SertifikasiController.cs
using _01.MiniProject234.Web.Models.Shared;
using _02.MiniProject234.ModelAccess;
using _03.MiniProject234.ModelView;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _01.MiniProject234.Web.Controllers
{
    public class SertifikasiController : Controller
    {
        // GET: x_sertifikat
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List(int paramPelamar)
        {
            return PartialView(x_sertifikasiModelAccess.GetDetailsByPelamar(paramPelamar));
        }

        public ActionResult Create()
        {
            ViewBag.ListTahunMulai = new SelectList(Common.GetYear(), "TahunMulai", "TahunMulai");
            ViewBag.ListTahunAkhir = new SelectList(CommonEndYear.GetYear(), "TahunAkhir", "TahunAkhir");
            //ViewBag.ListTahunAkhir = new SelectList(Common.UntilYear(int start_year), "TahunMulai", "TahunMulai");
            //ViewBag.
            return PartialView();
        }
        [HttpPost]
        public ActionResult Create(x_sertifikasiModelView paramModel)
        {
            try
            {
                paramModel.created_by = 1;
                paramModel.created_on = DateTime.Now;

                if (ModelState.IsValid)
                {
                    return Json(new
                    {
                        success = x_sertifikasiModelAccess.Insert(paramModel),
                        message = x_sertifikasiModelAccess.Message
                    }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    List<Message> listMessage =
                     Message.GetMessageErrorByModel("paramModel", ModelState);

                    return Json(new
                    {
                        success = false,
                        message = listMessage
                    }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception hasError)
            {
                return Json(new
                {
                    success = false,
                    message = hasError.Message
                }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Edit(Int32 paramId)
        {
            ViewBag.ListTahunMulai = new SelectList(Common.GetYear(), "TahunMulai", "TahunMulai");
            return PartialView(x_sertifikasiModelAccess.GetDetailsBy(paramId));
        }

        [HttpPost]
        public ActionResult EditPost(x_sertifikasiModelView paraModel)
        {
            try
            {
                paraModel.modified_by = 1;
                paraModel.modified_on = DateTime.Now;
                if (ModelState.IsValid)
                {
                    return Json(new
                    {
                        success = x_sertifikasiModelAccess.Update(paraModel),
                        message = x_sertifikasiModelAccess.Message
                    }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    List<Message> listMessage = Message.GetMessageErrorByModel("paraModel", ModelState);

                    return Json(new
                    {
                        success = false,
                        message = listMessage
                    }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception hasError)
            {
                return Json(new
                {
                    success = false,
                    message = hasError.Message
                }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Delete(Int32 paramId)
        {
            return PartialView(x_sertifikasiModelAccess.GetDetailsBy(paramId));
        }

        [HttpPost]
        public ActionResult Delete(x_sertifikasiModelView paraModel)
        {
            try
            {
                paraModel.deleted_by = 1;
                paraModel.deleted_on = DateTime.Now;
                return Json(new
                {
                    success = x_sertifikasiModelAccess.Delete(paraModel),
                    message = x_sertifikasiModelAccess.Message
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception hasError)
            {
                return Json(new
                {
                    success = false,
                    message = hasError.Message
                }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

MiniProject234/_01.MiniProject234.Web/Views/Sertifikasi/Create.cshtml
@model _03.MiniProject234.ModelView.x_sertifikasiModelView

<div class="modal-body" style="margin-left:20px;margin-right:20px">
    <div class="container py-5">

        <div class="col-md-12">
            <form id="form_create_sertifikasi">
                <div class="form-group row">
                    <div class="col-sm-6">
                        <label class="control-label" style="color: #023692">Nama&nbsp;Sertifikasi&nbsp;*</label>
                        @Html.EditorFor(model => model.certificate_name, new { htmlAttributes = new { @class = "form-control", @style = "width: 100%; max-width: 100%;" } })
                        <span class="field-validation-valid text-danger" data-valmsg-for="certificate_name" id="span_certificate_name" data-valmsg-replace="true"></span>
                    </div>
                    <div class="col-sm-6">
                        <label class="control-label" style="color: #023692">Penerbit&nbsp;*</label>
                        @Html.EditorFor(model => model.publisher, new { htmlAttributes = new { @class = "form-control", @style = "width: 100%; max-width: 100%;" } })
                        <span class="field-validation-valid text-danger" data-valmsg-for="publisher" id="span_publisher" data-valmsg-replace="true"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-3 field-list-start">
                        <label class="control-label" style="color: #023692">Berlaku mulai</label>
                        @Html.DropDownListFor(model => model.valid_start_month, new List<SelectListItem>
                        {
                           new SelectListItem{ Text="JANUARI", Value = "1" },
                           new SelectListItem{ Text="FEBRUARI", Value = "2" },
                           new SelectListItem{ Text="MARET", Value = "3" },
                           new SelectListItem{ Text="APRIL", Value = "4" },
                           new SelectListItem{ Text="MEI", Value = "5" },
                           new SelectListItem{ Text="JUNI", Value = "6" },
                           new SelectListItem{ Text="JULI", Value = "7" },
                           new SelectListItem{ Text="AGUSTUS", Value = "8" },
                           new SelectListItem{ Text="SEPTEMBER", Value = "9" },
                           new SelectListItem{ Text="OKTOBER", Value = "10" },
                           new SelectListItem{ Text="NOVEMBER", Value = "11" },
                           new SelectListItem{ Text="DESEMBER", Value = "12" }
                        }, "Pilih Bulan", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.valid_start_month, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-sm-3" field-list-until>
                        <label class="control-label">&nbsp;</label>
                        @Html.DropDownListFor(model => model.valid_start_year, (IEnumerable<SelectListItem>)ViewBag.ListTahunMulai, "Pilih Tahun", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.valid_start_year, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-sm-3">
                        <label class="control-label" style="color: #023692">Berlaku Sampai</label>
                        @Html.DropDownListFor(model => model.until_month, new List<SelectListItem>
                        {
                           new SelectListItem{ Text="JANUARI", Value = "1" },
                           new SelectListItem{ Text="FEBRUARI", Value = "2" },
                           new SelectListItem{ Text="MARET", Value = "3" },
                           new SelectListItem{ Text="APRIL", Value = "4" },
                           new SelectListItem{ Text="MEI", Value = "5" },
                           new SelectListItem{ Text="JUNI", Value = "6" },
                           new SelectListItem{ Text="JULI", Value = "7" },
                           new SelectListItem{ Text="AGUSTUS", Value = "8" },
                           new SelectListItem{ Text="SEPTEMBER", Value = "9" },
                           new SelectListItem{ Text="OKTOBER", Value = "10" },
                           new SelectListItem{ Text="NOVEMBER", Value = "11" },
                           new SelectListItem{ Text="DESEMBER", Value = "12" }
                        }, "Pilih Bulan", new { @class = "form-control" })
                        <span class="text-danger" id="untilmonth_error"></span>
                        @Html.ValidationMessageFor(model => model.until_month, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-sm-3">
                        <label class="control-label">&nbsp;</label>
                        @Html.DropDownListFor(model => model.until_year, (IEnumerable<SelectListItem>)ViewBag.ListTahunAkhir, "Pilih Tahun", new { @class = "form-control" })
                        <span class="text-danger" id="untilyear_error"></span>
                        @Html.ValidationMessageFor(model => model.until_year, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-12">
                        <label class="control-label" style="color: #023692">Catatan</label>
                        @Html.TextAreaFor(model => model.notes, 5, 40, htmlAttributes: new { @class = "form-control", @style = "width: 100%; max-width: 100%;" })
                        <span class="field-validation-valid text-danger" data-valmsg-for="notes" id="span_notes" data-valmsg-replace="true"></span>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal-footer">
    <div class="btn-group" role="group">
        <input type="button" title="Batal"
               value="Cancel" class="btn btn-default" id="btn_cancel_form"
               data-dismiss="modal" style="background-color:orange; color:white; width:100px; background-color: #FF6600" />
        <input type="button" title="Simpan"
               value="Save" class="btn btn-success btn_add_save_sertifikasi"
               id="btn_add_save_sertifikasi" style="background-color:darkblue; color:white; width:100px; background-color: #000066" />
    </div>
</div>


<script>
    //Disable Until Year & Month
    $(document).ready(function () {
        $("#until_year").attr('disabled', true);
        $("#until_month").attr('disabled', true);
        $("#valid_start_year").change(function () {
            if ($(this).val() != "") {
                $("#until_year").removeAttr("disabled");
                $("#until_month").removeAttr("disabled");
            }
        });
    });

</script>

<style>
    .btn {
        font-size: 16px;
    }

    .btn-default, .btn-success {
        border: none;
    }
</style>

MiniProject234/_01.MiniProject234.Web/Views/Sertifikasi/Delete.cshtml
@model _03.MiniProject234.ModelView.x_sertifikasiModelView

<div class="modal-body" style="width: 450px; height: 130px; margin:auto;">
    @Html.HiddenFor(model => model.id)
    <div class="alert-warning">
        <div class="col-md-3">
            <span class="glyphicon glyphicon-trash" style="color:red; font-size:50px"></span>
        </div>
        <div class="col-md-9">
            <center>
                Anda Yakin menghapus Keahlian
                <br />
                <label>@Html.DisplayFor(model => model.certificate_name)</label> ?
            </center>
        </div>
    </div>
</div>

<div class="modal-footer">
    <input type="button" value="Okay" title="Okay" class="btn btn-primary" id="btn_grid_delete_sertifikasi_confirm" />
    <input type="button" value="Tidak" title="Tidak" class="btn btn-danger" id="btn_cancel_form" data-dismiss="modal" />
</div>

MiniProject234/_01.MiniProject234.Web/Views/Sertifikasi/Edit.cshtml
@model _03.MiniProject234.ModelView.x_sertifikasiModelView

<div class="modal-body" style="margin-left:20px;margin-right:20px">
    <div class="container py-5">
        <div class="col-md-12">
            <form id="form_edit_sertifikasi">
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.id)
                <div class="form-group row">
                    <div class="col-sm-6">
                        <label class="control-label" style="color: #023692">Nama&nbsp;Sertifikasi&nbsp;*</label>
                        @Html.EditorFor(model => model.certificate_name, new { htmlAttributes = new { @class = "form-control", @style = "width: 100%; max-width: 100%;" } })
                        <span class="field-validation-valid text-danger" data-valmsg-for="certificate_name" id="span_certificate_name" data-valmsg-replace="true"></span>

                    </div>
                    <div class="col-sm-6">
                        <label class="control-label" style="color: #023692">Penerbit&nbsp;*</label>
                        @Html.EditorFor(model => model.publisher, new { htmlAttributes = new { @class = "form-control", @style = "width: 100%; max-width: 100%;" } })
                        <span class="field-validation-valid text-danger" data-valmsg-for="publisher" id="span_publisher" data-valmsg-replace="true"></span>

                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-3">
                        <label class="control-label" style="color: #023692">Berlaku mulai</label>
                        @Html.DropDownListFor(model => model.valid_start_month, new List<SelectListItem>
                        {
                           new SelectListItem{ Text="JANUARI", Value = "1" },
                           new SelectListItem{ Text="FEBRUARI", Value = "2" },
                           new SelectListItem{ Text="MARET", Value = "3" },
                           new SelectListItem{ Text="APRIL", Value = "4" },
                           new SelectListItem{ Text="MEI", Value = "5" },
                           new SelectListItem{ Text="JUNI", Value = "6" },
                           new SelectListItem{ Text="JULI", Value = "7" },
                           new SelectListItem{ Text="AGUSTUS", Value = "8" },
                           new SelectListItem{ Text="SEPTEMBER", Value = "9" },
                           new SelectListItem{ Text="OKTOBER", Value = "10" },
                           new SelectListItem{ Text="NOVEMBER", Value = "11" },
                           new SelectListItem{ Text="DESEMBER", Value = "12" }
                        }, "Pilih Bulan", new { @class = "form-control" })
                    </div>
                    <div class="col-sm-3">
                        <label class="control-label">&nbsp;</label>
                        @Html.DropDownListFor(model => model.valid_start_year, (IEnumerable<SelectListItem>)ViewBag.ListTahunMulai, "Pilih Tahun", new { @class = "form-control" })
                    </div>
                    <div class="col-sm-3">
                        <label class="control-label" style="color: #023692">Berlaku Sampai</label>
                        @Html.DropDownListFor(model => model.until_month, new List<SelectListItem>
                        {
                           new SelectListItem{ Text="JANUARI", Value = "1" },
                           new SelectListItem{ Text="FEBRUARI", Value = "2" },
                           new SelectListItem{ Text="MARET", Value = "3" },
                           new SelectListItem{ Text="APRIL", Value = "4" },
                           new SelectListItem{ Text="MEI", Value = "5" },
                           new SelectListItem{ Text="JUNI", Value = "6" },
                           new SelectListItem{ Text="JULI", Value = "7" },
                           new SelectListItem{ Text="AGUSTUS", Value = "8" },
                           new SelectListItem{ Text="SEPTEMBER", Value = "9" },
                           new SelectListItem{ Text="OKTOBER", Value = "10" },
                           new SelectListItem{ Text="NOVEMBER", Value = "11" },
                           new SelectListItem{ Text="DESEMBER", Value = "12" }
                        }, "Pilih Bulan", new { @class = "form-control" })
                        <span class="text-danger" id="untilmonth_error"></span>
                    </div>
                    <div class="col-sm-3">
                        <label class="control-label">&nbsp;</label>
                        @Html.DropDownListFor(model => model.until_year, (IEnumerable<SelectListItem>)ViewBag.ListTahunMulai, "Pilih Tahun", new { @class = "form-control" })
                        <span class="text-danger" id="untilyear_error"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-12">
                        <label class="control-label" style="color: #023692">Catatan</label>
                        @Html.TextAreaFor(model => model.notes, 5, 40, htmlAttributes: new { @class = "form-control", @style = "width: 100%; max-width: 100%;" })
                        <span class="field-validation-valid text-danger" data-valmsg-for="notes" id="span_notes" data-valmsg-replace="true"></span>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal-footer">
    <div class="btn-group" role="group">
        <input type="button" title="Batal"
               value="Cancel" class="btn btn-default" id="btn_cancel_form"
               data-dismiss="modal" style="background-color:orange; color:white; width:100px; background-color: #FF6600"/>
        <input type="button" title="Simpan"
               value="Save" class="btn btn-success"
               id="btn_grid_edit_save_sertifikasi" style="background-color:darkblue; color:white; width:100px; background-color: #000066" />
    </div>
</div>

<style>
    .btn {
        font-size: 16px;
    }
    .btn-default, .btn-success {
        border: none;
    }
</style>

MiniProject234/_01.MiniProject234.Web/Views/Sertifikasi/Index.cshtml
@{
    ViewBag.Title = "Master Sertifikasi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel-group">
    <div class="panel">
        <div class="panel-body">
            <div id="table-list" name="table-list">
                @Html.Partial("List")
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script type="text/javascript">
        var vjs_loading = '<div class="progress progress-bar-striped active" style="margin-bottom:0"><div class="progress-bar" style="width:100%"> </div></div>';

        $(document).ready(function () {
            ShowList();
        });

        //Method untuk menampilkan data
        function ShowList() {
            vjs_paged_lastRecordPerPage = $("#paging_size").val() == undefined ? 10 : $("#paging-size").val();
            $("#table-list").html(vjs_loading);
            $.ajax({
                url: '@Url.Action("List","Sertifikasi")',
                type: 'get',
                success: function (result) {
                    $("#table-list").html(result)
                }
            });
        }

    </script>
}

<style>
    .table {
        width: 100%;
        /*margin-bottom: 0px;*/
    }
</style>

MiniProject234/_01.MiniProject234.Web/Views/Sertifikasi/List.cshtml
@*@model System.Collections.Generic.IEnumerable<_03.MiniProject234.ModelView.x_sertifikasiModelView>*@
@model IEnumerable<_03.MiniProject234.ModelView.x_sertifikasiModelView>

<div class="input-group" style="display:flex; align-items:baseline;">
    <h2>Sertifikasi</h2>
    <a class="btn btn-link button_grid_create_sertifikasi" title="Create" name="Create">
        <span class="glyphicon glyphicon-plus-sign" style="font-size:26px;color:black"></span>
    </a>
</div>
<table class="table">
    <tr style="border-bottom:2pt solid #3B3B88;border-top:2pt solid #3B3B88">
        <th>
            <label class="control-label">NAMA SERTIFIKASI</label>
            @*@Html.DisplayNameFor(model => model.certificate_name)*@
        </th>
        <th>
            <label class="control-label">PENERBIT</label>
        </th>
        <th>
            <label class="control-label">MASA BERLAKU SERTIFIKASI</label>
        </th>
        <th>
            <label class="control-label">#</label>
        </th>
    </tr>

    @if (Model != null)
    {
        @*@Html.HiddenFor(model => model.id)*@
        foreach (var item in Model)
        {
            <tr>
                @Html.HiddenFor(modelItem => item.id)
                <td>
                    @Html.DisplayFor(modelItem => item.certificate_name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.publisher)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.valid_start_year)-@Html.DisplayFor(modelItem => item.valid_start_month) s.d @Html.DisplayFor(modelItem => item.until_year)-@Html.DisplayFor(modelItem => item.until_month)
                </td>
                <td class="dropdown">
                    <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                        More
                        <span class="caret" />
                    </a>
                    <ul class="dropdown-menu">
                        <li><a id="btn_grid_edit_sertifikasi" name="btn_grid_edit_sertifikasi" title="Edit Sertifikasi" data-id="@item.id">Ubah</a></li>
                        <li><a id="btn_grid_delete_sertifikasi" name="btn_grid_delete_sertifikasi" title="Edit Sertifikasi" data-id="@item.id">Hapus</a></li>
                    </ul>
                </td>
            </tr>
        }
    }
</table>

<style>
    table {
        padding: 20px;
    }

    h2 {
        color: #000066;
        font-weight: bold;
    }

    th {
        color: #1F1F78;
    }

    td {
        color: #383887;
    }
</style>